export const PERMISSIONS = {
  USER_CREATE: 'user.create',
  USER_VIEW: 'user.view',
  USER_UPDATE: 'user.update',
  USER_MANAGE_STATUS: 'user.manage_status',
  USER_ASSIGN_ROLE: 'user.assign_role',
  USER_MANAGE_PASSWORD: 'user.manage_password',
  ROLE_CREATE: 'role.create',
  ROLE_VIEW: 'role.view',
  ROLE_UPDATE: 'role.update',
  ROLE_ASSIGN_PERMISSION: 'role.assign_permission',
  PERMISSION_VIEW: 'permission.view',
  SALE_CREATE: 'sale.create',
  SALE_VIEW: 'sale.view',
  SALE_VOID: 'sale.void',
  SALE_REFUND: 'sale.refund',
  SALE_DISCOUNT: 'sale.discount',
  SALE_OVERRIDE_PRICE: 'sale.override_price',
  PRODUCT_CREATE: 'product.create',
  PRODUCT_EDIT: 'product.edit',
  PRODUCT_VIEW_COST: 'product.view_cost',
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_TRANSFER: 'inventory.transfer',
  PURCHASE_CREATE: 'purchase.create',
  PURCHASE_APPROVE: 'purchase.approve',
  PURCHASE_RECEIVE: 'purchase.receive',
  CUSTOMER_CREATE: 'customer.create',
  CUSTOMER_EDIT: 'customer.edit',
  SUPPLIER_CREATE: 'supplier.create',
  SUPPLIER_EDIT: 'supplier.edit',
  CASH_OPEN_SHIFT: 'cash.open_shift',
  CASH_CLOSE_SHIFT: 'cash.close_shift',
  REPORT_VIEW_SALES: 'report.view_sales',
  REPORT_VIEW_PROFIT: 'report.view_profit',
  SETTINGS_MANAGE: 'settings.manage',
} as const;

export const PERMISSION_CATALOG = Object.values(PERMISSIONS);
export type PermissionKey = (typeof PERMISSION_CATALOG)[number];
