packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

overrides:
  deepmerge-ts: 8.0.2
  mysql2: 3.23.1
  multer: 2.3.0

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  argon2: true
  esbuild: true
  prisma: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - argon2
  - esbuild
  - prisma
  - '@scarf/scarf'
  - sharp
  - unrs-resolver
