process.env.NODE_ENV = 'test';
process.env.DATABASE_URL ??= 'postgresql://vendo:change_me@localhost:5432/vendo?schema=public';
process.env.JWT_ACCESS_SECRET ??= 'test_access_secret_at_least_32_characters_long';
process.env.JWT_REFRESH_SECRET ??= 'test_refresh_secret_at_least_32_characters_long';
process.env.JWT_ISSUER ??= 'vendo-api-test';
process.env.JWT_AUDIENCE ??= 'vendo-web-test';
process.env.ACCESS_TOKEN_TTL ??= '15m';
process.env.REFRESH_TOKEN_TTL ??= '30d';
process.env.PASSWORD_RESET_TTL ??= '30m';
