import {
  ArrowLeft,
  ArrowLeftRight,
  Badge,
  BadgeDollarSign,
  BadgePlus,
  Banknote,
  Bath,
  Box,
  Boxes,
  Building2,
  CalendarDays,
  ChartNoAxesCombined,
  ChartPie,
  ChartSpline,
  CircleArrowDown,
  CircleArrowUp,
  CircleCheck,
  CircleDollarSign,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  ClockAlert,
  ClockArrowUp,
  CreditCard,
  Ellipsis,
  Eye,
  Factory,
  FileText,
  Files,
  FileUp,
  GitBranch,
  Grid2X2,
  HandCoins,
  Handshake,
  History,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Layers3,
  LayoutDashboard,
  ListFilter,
  LoaderCircle,
  LockKeyhole,
  MonitorSmartphone,
  Package,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  PackageX,
  Palette,
  PauseCircle,
  Pencil,
  Plus,
  Printer,
  ReceiptText,
  RefreshCw,
  Repeat2,
  Ruler,
  Save,
  ScanBarcode,
  ScrollText,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Tags,
  TrendingUp,
  TriangleAlert,
  Truck,
  Undo2,
  User,
  UserCog,
  UserRound,
  Users,
  UsersRound,
  Vault,
  WalletCards,
  Warehouse,
  X,
  type LucideIcon,
} from 'lucide-react';
import type { ComponentProps } from 'react';

export const iconRegistry = {
  dashboard: LayoutDashboard,
  pos: MonitorSmartphone,
  sales: BadgeDollarSign,
  purchasing: ShoppingBag,
  products: PackageOpen,
  inventory: Boxes,
  customers: Users,
  suppliers: Truck,
  cash: Banknote,
  expenses: WalletCards,
  reports: ChartNoAxesCombined,
  administration: ShieldCheck,
  settings: Settings,
  barcode: ScanBarcode,
  cart: ShoppingCart,
  receipt: ReceiptText,
  invoice: FileText,
  payment: CreditCard,
  due: ClockAlert,
  refund: HandCoins,
  return: Undo2,
  exchange: Repeat2,
  holdSale: PauseCircle,
  product: Package,
  tile: Grid2X2,
  sanitary: Bath,
  category: Tags,
  brand: Badge,
  manufacturer: Factory,
  unit: Ruler,
  stock: Layers3,
  box: Box,
  warehouse: Warehouse,
  batch: PackageCheck,
  shade: Palette,
  transfer: ArrowLeftRight,
  physicalCount: ClipboardCheck,
  adjustment: SlidersHorizontal,
  damageLoss: PackageX,
  movementHistory: History,
  purchaseOrder: ClipboardList,
  goodsReceipt: PackagePlus,
  supplierInvoice: Files,
  supplierPayment: CircleDollarSign,
  purchaseReturn: PackageMinus,
  customer: UserRound,
  customerGroup: UsersRound,
  supplier: Handshake,
  receivable: Landmark,
  advance: BadgePlus,
  cashRegister: Vault,
  cashShift: ClockArrowUp,
  cashIn: CircleArrowDown,
  cashOut: CircleArrowUp,
  expense: WalletCards,
  profit: TrendingUp,
  analytics: ChartSpline,
  calendar: CalendarDays,
  financialSummary: ChartPie,
  company: Building2,
  branch: GitBranch,
  user: User,
  role: UserCog,
  permission: KeyRound,
  security: LockKeyhole,
  auditLog: ScrollText,
  add: Plus,
  edit: Pencil,
  search: Search,
  filter: ListFilter,
  refresh: RefreshCw,
  close: X,
  more: Ellipsis,
  print: Printer,
  export: FileUp,
  view: Eye,
  back: ArrowLeft,
  save: Save,
  success: CircleCheck,
  warning: TriangleAlert,
  error: CircleX,
  info: Info,
  loading: LoaderCircle,
  empty: Inbox,
  lowStock: PackageSearch,
} satisfies Record<string, LucideIcon>;

export type VendoIconName = keyof typeof iconRegistry;
export type VendoIconSize = 16 | 18 | 20 | 24;

export function VendoIcon({
  name,
  size = 18,
  strokeWidth = 1.75,
  ...props
}: Omit<ComponentProps<'svg'>, 'name' | 'ref' | 'size'> & {
  name: VendoIconName;
  size?: VendoIconSize;
  strokeWidth?: number;
}) {
  const Icon = iconRegistry[name];
  return (
    <Icon aria-hidden="true" focusable="false" size={size} strokeWidth={strokeWidth} {...props} />
  );
}
